project:
  type: website

website:
  title: "Tim's Blog"
  navbar:
    search: true
    # right:
  #     - icon: github
  #       href: https://github.com/timkoval
  #     - icon: twitter
  #       href: https://twitter.com/timk0val
  open-graph: true
  site-url: "https://timkoval.io/"
format:
  html:
    theme: litera
    css: styles.css
